<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Configurations>Debug;Release</Configurations>
    <Platforms>AnyCPU;ARM64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mime\Mime.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == ''">
    <Arch>$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)</Arch>
    <RuntimeIdentifier Condition=" '$([MSBuild]::IsOSPlatform(Windows))' ">win-$(Arch.ToLower())</RuntimeIdentifier>
    <RuntimeIdentifier Condition=" '$([MSBuild]::IsOSPlatform(Linux))' ">linux-$(Arch.ToLower())</RuntimeIdentifier>
    <RuntimeIdentifier Condition=" '$([MSBuild]::IsOSPlatform(OSX))' ">osx-$(Arch.ToLower())</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)/../../src/Magic/runtimes/$(RuntimeIdentifier)') ">
    <NativeLib Include="$(MSBuildProjectDirectory)/../../src/Magic/runtimes/$(RuntimeIdentifier)/native/*" />
  </ItemGroup>

  <Target Name="CopyNativeLib" AfterTargets="Build">
    <Copy SourceFiles="@(NativeLib)" DestinationFolder="$(OutputPath)" />
  </Target>

  <ItemGroup>
    <None Include="TestData/**/*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="../../src/Magic/content/magic.mgc" Link="magic.mgc" />
  </ItemGroup>

  <Target Name="PrintRID" BeforeTargets="Build">
    <Message Text="Current runtime: $(RuntimeIdentifier)" Importance="high" />
  </Target>

</Project>
