<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Choose>
		<When Condition="('$(Platform)' == 'AnyCPU') OR ('$(Platform)' == 'x86') OR ('$(Platform)' == 'Win32')">
			<ItemGroup>
				<None Include="@(LibMagicX86)">
					<Link>x86\%(RecursiveDir)%(FileName)%(Extension)</Link>
					<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
					<PublishState>Included</PublishState>
					<Visible>false</Visible>
				</None>
			</ItemGroup>
		</When>
	</Choose>

	<Choose>
		<When Condition="('$(Platform)' == 'AnyCPU') OR ('$(Platform)' == 'x64')">
			<ItemGroup>
				<None Include="@(LibMagicX64)">
					<Link>x64\%(RecursiveDir)%(FileName)%(Extension)</Link>
					<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
					<PublishState>Included</PublishState>
					<Visible>false</Visible>
				</None>
			</ItemGroup>
		</When>
	</Choose>

	<Choose>
		<When Condition="('$(Platform)' == 'AnyCPU') OR ('$(Platform)' == 'ARM64')">
			<ItemGroup>
				<None Include="@(LibMagicARM64)">
					<Link>arm64\%(RecursiveDir)%(FileName)%(Extension)</Link>
					<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
					<PublishState>Included</PublishState>
					<Visible>false</Visible>
				</None>
			</ItemGroup>
		</When>
	</Choose>

	<UsingTask TaskName="TransformXml" AssemblyFile="$(MSBuildThisFileDirectory)..\tools\SlowCheetah.dll" />
	<Target Name="Magic_TransformConfig" AfterTargets="_CopyAppConfigFile" Condition="'@(AppConfigWithTargetPath)' != ''">
		<TransformXml
		  Source="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"
		  Transform="$(MSBuildThisFileDirectory)..\transform\Magic.NetFramework.app.config.x86.transform"
		  Destination="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"
		  Condition="('$(Platform)' == 'AnyCPU') OR ('$(Platform)' == 'x86') OR ('$(Platform)' == 'Win32')"
		/>
		
		<TransformXml
		  Source="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"
		  Transform="$(MSBuildThisFileDirectory)..\transform\Magic.NetFramework.app.config.x64.transform"
		  Destination="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"
		  Condition="('$(Platform)' == 'AnyCPU') OR ('$(Platform)' == 'x64')"
		/>

		<TransformXml
		  Source="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"
		  Transform="$(MSBuildThisFileDirectory)..\transform\Magic.NetFramework.app.config.arm64.transform"
		  Destination="@(AppConfigWithTargetPath->'$(OutDir)%(TargetPath)')"
		  Condition="('$(Platform)' == 'AnyCPU') OR ('$(Platform)' == 'ARM64')"
		/>
	</Target>
	
	<ItemGroup>
		<Content Include="$(MSBuildThisFileDirectory)..\contentfiles\magic.mgc" CopyToOutputDirectory="PreserveNewest" 	/>
	</ItemGroup>
</Project>